package xyy.note.mybatis.mbg.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xyy.note.mybatis.mbg.model.AccountInfo;
import xyy.note.mybatis.mbg.model.AccountInfoExample;

public interface AccountInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    long countByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    int deleteByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    int insert(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    int insertSelective(AccountInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    List<AccountInfo> selectByExample(AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_info
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    int updateByExample(@Param("record") AccountInfo record, @Param("example") AccountInfoExample example);
}