package xyy.note.mybatis.mbg.model;

import java.util.Date;

public class AccountInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.id
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.account
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.amount
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_info.creat_at
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    private Date creat_at;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.id
     *
     * @return the value of account_info.id
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.id
     *
     * @param id the value for account_info.id
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.account
     *
     * @return the value of account_info.account
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.account
     *
     * @param account the value for account_info.account
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.amount
     *
     * @return the value of account_info.amount
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.amount
     *
     * @param amount the value for account_info.amount
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_info.creat_at
     *
     * @return the value of account_info.creat_at
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public Date getCreat_at() {
        return creat_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_info.creat_at
     *
     * @param creat_at the value for account_info.creat_at
     *
     * @mbg.generated Sat Mar 11 12:18:27 CST 2017
     */
    public void setCreat_at(Date creat_at) {
        this.creat_at = creat_at;
    }
}